version: "3.8"

services:
  django_app:
    image: django_app
    build:
      context: ./odoo-bhs
    container_name: "django"
    ports:
      - 8000:8000
    env_file:
      - "./odoo-bhs/.env"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - data:/var/lib/mysql
volumes:
  data: