version: "3.8"

services:
  django_app:
    image: django_app
    build:
      context: .
    container_name: "django"
    ports:
      - 8880:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./odoo:/django/odoo
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/nc:/usr/bin/nc
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
