# Generated by Django 5.0.6 on 2024-07-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('modules', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('odoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.odoo')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='demo',
            field=models.ManyToManyField(to='base.demo'),
        ),
    ]
