# Generated by Django 5.0.6 on 2024-07-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_demo_module_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='odoo',
            new_name='version',
        ),
    ]
