# Generated by Django 5.0.6 on 2024-07-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_odoo_demo_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='modules',
        ),
    ]
