# Generated by Django 5.0.6 on 2024-07-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_demo_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='state',
            field=models.CharField(choices=[('Starting', 'Starting'), ('Running', 'Running'), ('Stopped', 'Stopped'), ('Destroyed', 'Destroyed')], default='Starting', max_length=15),
        ),
    ]
