# Generated by Django 5.0.6 on 2024-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
