# Generated by Django 5.0.6 on 2024-07-05 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_port_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
