# Generated by Django 5.0.6 on 2024-07-05 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_demo_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
